use bon::Builder;
use omp_core::Str;

use crate::{Cost, Props, Unsupported, Usage};

/// Time window relative to the current date.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SearchRecency {
	/// Results from the last day.
	Day,
	/// Results from the last week.
	Week,
	/// Results from the last month.
	Month,
	/// Results from the last year.
	Year,
}

/// Search-engine content filtering level.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SafeSearch {
	/// Disable engine filtering.
	Off,
	/// Apply balanced filtering.
	Moderate,
	/// Apply strict filtering.
	Strict,
}

/// Geographic bias supplied to search engines that support native location
/// controls.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Eq, PartialEq)]
pub struct SearchLocation {
	/// City name.
	pub city:     Str,
	/// State, province, or region name.
	pub region:   Str,
	/// Country name or code accepted by the selected engine.
	pub country:  Str,
	/// IANA timezone identifier.
	pub timezone: Str,
}

/// Web search request spanning raw, synthesized, and hybrid engines.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct SearchRequest {
	/// User query.
	pub query:            Str,
	/// Maximum results; zero preserves the engine default.
	pub limit:            u32,
	/// Optional relative publication window.
	pub recency:          Option<SearchRecency>,
	/// Inclusive ISO date lower bound, empty when unbounded.
	pub after:            Str,
	/// Inclusive ISO date upper bound, empty when unbounded.
	pub before:           Str,
	/// Domain allowlist.
	#[allow(clippy::struct_field_names, reason = "matches the wire search request vocabulary")]
	pub allowed_domains:  Vec<Str>,
	/// Domain denylist.
	pub excluded_domains: Vec<Str>,
	/// ISO 3166-1 alpha-2 country bias.
	pub country:          Str,
	/// ISO-639-1 result language.
	pub language:         Str,
	/// Optional detailed geographic bias.
	pub location:         Option<SearchLocation>,
	/// Optional engine content filtering level.
	pub safesearch:       Option<SafeSearch>,
	/// Explicit engine id; empty selects the registry fallback chain.
	pub engine:           Str,
	/// Request deadline; zero preserves the server default.
	pub timeout_ms:       u32,
	/// Namespaced engine-specific controls.
	pub props:            Props,
}

/// One retrieved search result.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct SearchSource {
	/// Canonical result URL.
	pub url:          Str,
	/// Result title.
	pub title:        Str,
	/// Engine-provided excerpt.
	pub snippet:      Str,
	/// ISO publication date or datetime when known.
	pub published_at: Str,
	/// Author or publisher attribution.
	pub author:       Str,
	/// Engine-relative relevance from zero through one when reported.
	pub score:        Option<f64>,
}

/// Citation linking a synthesized answer span to a source.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Eq, PartialEq)]
pub struct SearchCitation {
	/// Cited source URL.
	pub url:        Str,
	/// Cited source title.
	pub title:      Str,
	/// Text attributed to the source.
	pub cited_text: Str,
	/// Optional starting byte offset in the synthesized answer.
	pub start:      Option<u32>,
	/// Optional ending byte offset in the synthesized answer.
	pub end:        Option<u32>,
}

/// Search result envelope covering raw hits and optional synthesized narrative.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct SearchResponse {
	/// Engine that served the query after fallback resolution.
	pub engine:         Str,
	/// Synthesized answer, empty for raw-result engines.
	pub answer:         Str,
	/// Retrieved hits available for every engine paradigm.
	pub sources:        Vec<SearchSource>,
	/// Inline source anchors for the synthesized answer.
	pub citations:      Vec<SearchCitation>,
	/// Subqueries generated by the engine.
	pub search_queries: Vec<Str>,
	/// Related follow-up queries.
	pub related:        Vec<Str>,
	/// Diagnostics such as relaxed directives used to avoid zero results.
	pub warnings:       Vec<Str>,
	/// Provider usage when available.
	pub usage:          Option<Usage>,
	/// Metered cost when available.
	pub cost:           Option<Cost>,
	/// Controls changed or omitted by the provider path.
	pub unsupported:    Vec<Unsupported>,
	/// Namespaced result metadata.
	pub props:          Props,
}
