use bon::Builder;
use bytes::Bytes;
use omp_core::SmolStr;

use super::{Props, ids::CallId};

/// A complete canonical conversation used by stateless turns and context
/// reseeding.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Default, PartialEq)]
pub struct Thread {
	/// Transcript entries in conversation order.
	pub items: Vec<Item>,
}

/// One transcript entry, assigned a dense sequence number when the gateway
/// commits a turn.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct Item {
	/// Commit sequence; callers use zero before the gateway assigns the durable
	/// sequence.
	pub seq:           u64,
	/// Creation time in Unix epoch milliseconds, or zero when the source did
	/// not supply one.
	#[builder(default)]
	pub created_at_ms: u64,
	/// The semantic transcript entry.
	pub kind:          ItemKind,
	/// Namespaced extension data retained across projection and replay.
	pub props:         Props,
}

/// Semantic forms admitted to the canonical transcript.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq)]
pub enum ItemKind {
	/// A role-addressed model or caller message.
	Message(Message),
	/// A canonical tool invocation minted by omp.
	ToolCall(ToolCall),
	/// The result paired with an earlier invocation.
	ToolResult(ToolResult),
}

/// A portable conversation role; codecs decide whether system maps to system,
/// developer, or instructions.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Role {
	/// Instructions supplied by the application rather than an end user.
	System,
	/// Input supplied by the end user.
	User,
	/// Output generated by the model.
	Assistant,
}

/// A role-addressed sequence of content parts.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct Message {
	/// Portable author role projected by each transport.
	pub role:  Role,
	/// Ordered multimodal content.
	pub parts: Vec<Part>,
}

/// One portable piece of message or tool-result content.
///
/// Every media kind is blob-shaped. Inline visibility, thumbnailing, and
/// stubbing are projection policy rather than distinct part variants.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq)]
pub enum Part {
	/// Visible UTF-8 content.
	Text(SmolStr),
	/// Replayable model reasoning, which may be opaque or redacted.
	Thinking(Thinking),
	/// Content-addressed binary media.
	Blob(BlobPart),
	/// Provider-reported model fallback boundary retained for replay.
	Fallback(ModelFallback),
	/// Provider-hosted tool call or result retained for replay.
	ServerTool(ServerTool),
}

/// Model reasoning retained so providers that sign reasoning can accept later
/// turns.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Eq, PartialEq)]
pub struct Thinking {
	/// Visible reasoning text, empty for an opaque redacted payload.
	pub text:      SmolStr,
	/// Provider replay signature preserved verbatim across turns.
	pub signature: Bytes,
	/// Whether the signature contains an opaque redacted payload rather than
	/// signing visible text.
	pub redacted:  bool,
}

/// Provider-reported model transition within one assistant response.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Eq, PartialEq)]
pub struct ModelFallback {
	/// Model that began serving the response.
	pub from_model: SmolStr,
	/// Model that continued serving after fallback.
	pub to_model:   SmolStr,
}

/// Provider-hosted tool block retained as native history.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct ServerTool {
	/// Provider namespace that owns the hosted tool semantics.
	pub provider:          SmolStr,
	/// Whether this block invokes the hosted tool or reports its result.
	pub kind:              ServerToolKind,
	/// Provider call identity used to pair call and result blocks.
	pub id:                SmolStr,
	/// Provider wire tool name.
	pub name:              SmolStr,
	/// UTF-8 JSON input or result content retained verbatim.
	pub payload_json:      Bytes,
	/// Namespaced provider metadata needed for faithful replay.
	pub provider_metadata: Option<Props>,
}

/// Direction of a provider-hosted tool block.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ServerToolKind {
	/// Provider-side invocation.
	Call,
	/// Provider-side result.
	Result,
}

/// A native content part carrying the data needed to resolve or inline a
/// content-addressed payload.
///
/// [`omp_proto::thread::v1::Blob`] is its process-boundary wire binding, while
/// `omp_storage::blob::BlobRef` is the smaller store handle containing only
/// hash and size. This type additionally retains MIME and optional inline bytes
/// because it is the conversation part.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Eq, PartialEq)]
pub struct BlobPart {
	/// BLAKE3-256 digest used to resolve the payload in the daemon blob store.
	pub hash:   [u8; 32],
	/// Media type used when projecting the payload into a provider request.
	pub mime:   SmolStr,
	/// Original payload length, retained even when only the hash is sent.
	pub size:   u64,
	/// Small inline payload for peers that cannot access the shared blob store.
	pub inline: Bytes,
	/// Provider resolution hint for image payloads.
	pub detail: Option<ImageDetail>,
}

/// Resolution hint for an image payload.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ImageDetail {
	/// Let the provider choose the resolution.
	Auto,
	/// Prefer a lower-resolution representation.
	Low,
	/// Prefer a high-resolution representation.
	High,
	/// Preserve the original image resolution.
	Original,
}

/// A canonical invocation whose id is translated to provider-specific
/// constraints only at the edge.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct ToolCall {
	/// Omp-minted identity used to correlate calls and results independent of
	/// provider ids.
	pub id:                CallId,
	/// Portable tool dispatch name.
	pub name:              SmolStr,
	/// UTF-8 JSON arguments retained as bytes for tolerant parsing and zero-copy
	/// transport.
	pub args_json:         Bytes,
	/// Provider thought signature attached to Gemini-style calls and replayed
	/// verbatim.
	pub thought_signature: Bytes,
	/// Harness-level intent extracted from traced tool arguments.
	pub intent:            Option<SmolStr>,
	/// Verbatim in-band syntax that produced a synthetic call.
	pub raw:               Option<Bytes>,
	/// Original provider custom-tool wire name.
	pub custom_wire_name:  Option<SmolStr>,
	/// Namespaced provider metadata needed for execution and replay.
	pub provider_metadata: Option<Props>,
}

/// Output paired with a canonical tool invocation.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, PartialEq)]
pub struct ToolResult {
	/// Identity of the invocation this result answers.
	pub call_id:           CallId,
	/// Harness tool name carried independently because some transports require
	/// it on the result wire and the matching call may no longer be in the
	/// thread.
	pub name:              SmolStr,
	/// Ordered text or media returned by the tool.
	pub parts:             Vec<Part>,
	/// Whether the tool reported failure rather than a normal result.
	pub is_error:          bool,
	/// Tool-specific structured detail retained for callers.
	pub details:           Option<serde_json::Value>,
	/// Who initiated the tool result.
	pub attribution:       Option<MessageAttribution>,
	/// Unix epoch milliseconds when the result was pruned.
	pub pruned_at_ms:      Option<u64>,
	/// Whether the consumed result carried no useful retained information.
	pub useless:           Option<bool>,
	/// Namespaced provider metadata needed for faithful replay.
	pub provider_metadata: Option<Props>,
}

/// Attribution for a historical message or tool result.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum MessageAttribution {
	/// End-user initiated.
	User,
	/// Agent or harness initiated.
	Agent,
}

/// Optimistic-concurrency stamp for a server-held conversation.
///
/// The monotone head prevents stale writes while the opaque integrity token
/// catches equal-length divergent histories; a mismatch is always a conflict
/// and never an implicit truncation.
#[non_exhaustive]
#[derive(Builder, Clone, Debug, Eq, Hash, PartialEq)]
pub struct Revision {
	/// Sequence of the last committed item, or zero for an empty thread.
	pub head:  u64,
	/// Server-defined integrity token over the committed history.
	pub token: Bytes,
}
